name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.205'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --no-restore

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.205'

    - name: Restore dependencies
      run: dotnet restore

    - name: Run unit tests with coverage
      run: |
        dotnet test --collect:"XPlat Code Coverage"
      env:
        PATH: ${{ runner.tool_cache }}/dotnet-tools/:$PATH

    - name: Install ReportGenerator tool locally
      run: |
        dotnet new tool-manifest
        dotnet tool install dotnet-reportgenerator-globaltool

    - name: List installed tools
      run: dotnet tool list

    - name: Generate coverage report
      run: |
        dotnet reportgenerator -reports:"**/coverage.cobertura.xml" -targetdir:"coverage-report" -reporttypes:Html
      env:
        PATH: ~/.dotnet/tools:$PATH

    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage-report

  check-coverage:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Download coverage report
      uses: actions/download-artifact@v3
      with:
        name: coverage-report
        path: coverage-report

    - name: Verify coverage
      run: |
        if [ ! -f "coverage-report/index.htm" ]; then
          echo "Coverage report index.htm not found!"
          exit 1
        fi

        coverage_percentage=$(grep -oP 'Total Line Coverage: \K[0-9]+' coverage-report/index.htm || echo "0")
        if [ "$coverage_percentage" -lt 90 ]; then
          echo "Test coverage is below 90%. Current coverage: $coverage_percentage%"
          exit 1
        else
          echo "Test coverage is above 90%. Current coverage: $coverage_percentage%"
        fi
